### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by atesgoral** [atesgoral/hrm-solutions#113]
Could have better looks than the README.md, and could allow dynamic features like pulling in level info from hrm-level-data, and even the ability run programs right inside the browser.

**Comment by AlanDeSmet** [comment]
For the sake of sanity, some level of automated generation seems like a good idea.  I'm fond of Markdown as a human-writable language.

Here's a proposal, which I hope is useful if only as a strawman.
1. Move entire thing to a gh-pages branch. Declare the master branch dead. (Kinda a shame GitHub doesn't have an option to make the master branch the GitHub Pages branch.)
2. Maintain web pages in Markdown. Keep them in the top level directory.
3. Symlink README.md to index.md. This way it will remain visible in the GitHub browser and will serve as the main page in GitHub pages.
4. Whip up a Javascript program to process an .md file and write a matching .html file.  Steps would be:
  - Sneak in a <link> to CSS.
  - Add common elements: link to main page, footers, etc.
  - Look for relative (same host) links to \*.asm files. Rewrite them to go to a wrapper page which would provide a viewer, download option, possibly a matching level view, and ultimately maybe a simulator.  Use a single page that takes arguments to the asm file, something like codeview.html?u=14-Maximization-Room-10.34/10.34-unframework.asm . ([Proposal for starting wrapping page](https://alandesmet.github.io/human-resource-machine-viewer/example.html?u=36-Alphabetizer.size.speed.asm&t=Solution+for+floor+36:+Alphabetizer)
5. Hook up Gulp configuration to run that new program on \*.md files and write matching .html files.
6. Maybe at some future date have a special TABLE\_OF\_WINNERS in the main page that the program will replace with an automatically generated table.

I've implemented md2html programs before, although not in Javascript. It _seems_ like it would be straightforward.

**Comment by atesgoral** [comment]
The markdown approach would be neat if we have multiple pages. But I was initially thinking of a simple single page application that can pull in hrm-level-data via XHR and therefore not require page compilation. The solutions in the repo could then be compiled into JSON that can be pulled via XHR as well. Since I already have solution validation + execution in CI, the extra step of compiling results into JSON and deploying somewhere would be tiny.

**Comment by AlanDeSmet** [comment]
Are you intending to have that single page acting as both the index and the viewer for solutions? It seems like it might be a simpler implementation to break those into two different pages.

How will the single page find the solutions? Or is that part of the compiling to JSON you're imagining, some sort of creation of an index?

Relatedly, presumably the single page, when acting as an index, would want to be able to provide useful information about the varying solutions.  Sometimes it's obvious (this one makes speed par, that one makes size par), but given the expanded goals of the archive that doesn't necessarily seem like enough.

Are you proposing a JSON file per solution, and that JSON would basically be the assembly, but as JSON?  If so, what benefits are you seeing?

Related

**Comment by atesgoral** [comment]
I'm still pondering about this :)

**Comment by atesgoral** [comment]
@nanashi-juanto Soon, we won't have to manually maintain the Top Scores table! http://atesgoral.github.io/hrm-solutions/

**Comment by nanashi-juanto** [comment]
Neat. I'm jelly since I can barely write simple scripts. I was literally playing housekeeper boy (or something).

**Comment by nrkn** [comment]
FYI if you wanna reduce deps hrm-parser now has an async callback that gives you metadata like source comments, image labels, image comments etc.

**Comment by atesgoral** [comment]
Cool!

**Comment by atesgoral** [comment]
Done: http://atesgoral.github.io/hrm-solutions/

Top Scores are now automatically determined from existing solutions.

Contributors are still manually maintained (because GitHub doesn't report on GitHub accounts with unverified emails), but they're now in a more easily maintained contributors.yml file.

Split the contributor / non-contributor related information across README.md and gh-pages.

**Comment by nrkn** [comment]
Hadn't noticed `successRatio` before - that's cool

**Comment by atesgoral** [comment]
Added level info to Top Scores
