### ISSUE TITLE
Registry of solutions so other projects can programatically access solutions

### ISSUE THREAD

**Issue by sixlettervariables** [atesgoral/hrm-solutions#132]
A registry would be nice, either via a JSON file (maintained per PR) or an `index.js` which could return the solutions for some level `n`. This would let me wire up `hrm-level-data`, `hrm-level-inbox-generator`, `hrm-level-outbox-generator`, and `hrm-solutions` as a set to feed my sandbox (or any other emulator, really).

Pseudocode:
```javascript
var levels = require('hrm-level-data');
var inboxer = require('hrm-level-inbox-generator');
var outboxer = require('hrm-level-outbox-generator');
var solutions = require('hrm-solutions');

levels.forEach(function (level) {
  var inbox = inboxer.generate(level.number);
  var outbox = outboxer.generate(level.number, inbox);
  if (inbox === null || outbox === null) {
    inbox = level.examples[0].inbox.splice();
    outbox = level.examples[0].outbox.splice();
  }

  // the Solution Registry tie-in here
  solutions.getSolutions(level.number, function (solution) {
     // execute `solution`
     var results = hrm.execute(solution, { inbox: inbox, variables: level.floor.tiles.splice() });
     if (!testOutboxes(results.outbox, outbox)) {
        // bad
     }
  });
});
```

**Comment by atesgoral** [comment]
I'm planning to publish an automatically generated JSON and/or JSONP response for external consumption. Soon...

**Comment by atesgoral** [comment]
The inbox and outbox generators are now published by the way.

**Comment by sixlettervariables** [comment]
Awesome, thank you!

**Comment by atesgoral** [comment]
Got a first cut working: http://atesgoral.github.io/hrm-solutions/manifest.json (This is automatically updated each time a PR is merged).

**Comment by atesgoral** [comment]
@nanashi-juanto We're getting close to having the ability to automatically deduce specific/obsolete etc. type modifiers for filenames.

**Comment by atesgoral** [comment]
Tweaked the naming convention a bit:

http://atesgoral.github.io/hrm-solutions/data/index.json
http://atesgoral.github.io/hrm-solutions/data/index.js

**Comment by atesgoral** [comment]
I'm planning to take out the program sources from the top-level index to reduce its size and create a path hierarchy as follows:

http://atesgoral.github.io/hrm-solutions/data/index.json (all solutions, without source)
http://atesgoral.github.io/hrm-solutions/data/5/index.json (all solutions for level 5, without source)
http://atesgoral.github.io/hrm-solutions/data/5/51945f0fae04ec5b46d2799f0f1987fa.json (specific solution, with source - the key is the md5 hash of the source)

**Comment by atesgoral** [comment]
@sixlettervariables, @nrkn, @AlanDeSmet FYI. Updated Data API section in README.md with API info.
