### ISSUE TITLE
Hey check out this thread

### ISSUE THREAD

**Issue by Mygod** [atesgoral/hrm-solutions#135]
http://goofans.com/forum/more-2d-boys/human-resource-machine/14076
Some of them beat the solution in this repo.

**Comment by Mygod** [comment]
For example 38 - 24/30 by me.

**Comment by Mygod** [comment]
8 speed 17, 10 speed 26, 11 speed 35, 12 speed 41 by MOM4Evr, a.k.a. @meh2481.
And umm that's it.

**Comment by Mygod** [comment]
See #136.

**Comment by atesgoral** [comment]
:+1: For the forum link!
