### ISSUE TITLE
Move solution folders to /solutions top-level folder

### ISSUE THREAD

**Issue by atesgoral** [atesgoral/hrm-solutions#139]
To reduce clutter, to bring README content into the fold, and to easily ensure Gulp tasks just iterate over actual solution files.

**Comment by atesgoral** [comment]
@nanashi-juanto What do you think? I actually have reservations about this because this would prevent the level folders from being seen at a glance.

**Comment by nanashi-juanto** [comment]
@atesgoral If it makes things easier on your side, sure.

**Comment by atesgoral** [comment]
@nanashi-juanto I realized there's no compelling reason to move the folders. Closing.

**Comment by atesgoral** [comment]
OK I found a reason, and going ahead with this :)
