### ISSUE TITLE
Simulator is sorting numbers as strings

### ISSUE THREAD

**Issue by mrflip** [atesgoral/hrm-solutions#262]
The simulator is incorrectly showing sort solutions as failing, because it is sorting `10` before `2`:

```
input:
[ 7, 10, 6, 6, 5, 7, 6, 2, 4, 0, 'M', 'K', 'R', 'W', 0, 3, 2, 5, 5, 10, 3, 6, 5, 7, 8, 0 ]
expected:
[ 10, 2, 4, 5, 6, 6, 6, 7, 7, 'K', 'M', 'R', 'W', 10, 2, 3, 3, 5, 5, 5, 6, 7, 8 ]
actual:
[ 2, 4, 5, 6, 6, 6, 7, 7, 10, 'K', 'M', 'R', 'W', 2, 3, 3, 5, 5, 5, 6, 7, 8, 10 ]
```

One solution is to remove 10 from the test pool. Another is to fix the problem.

**Comment by sniperrifle2004** [comment]
I feel I should mention I created this issue a while ago: https://github.com/atesgoral/hrm-level-outbox-generator/issues/1 
with a corresponding pull request, when I noticed my sort programs were failing tests. It only provides a fix for 41.

**Comment by mrflip** [comment]
You are correct – I didn't notice the issue or the PR, should have checked over there first. I put in a PR that addresses 4, 28 and 41 before seeing this.

**Comment by atesgoral** [comment]
OMG. I just saw this now. My apologies.
