### ISSUE TITLE
Programatically check solutions

### ISSUE THREAD

**Issue by nrkn** [atesgoral/hrm-solutions#92]
Hi - I'm really not sure that an issue is the best way to communicate this, but just wanted to say that if you want to programatically check the solutions, I made a runtime that executes HRM asm files in javascript:

https://github.com/nrkn/hrm-cpu

See the test folder to see how you would batch check multiple solutions - I'm currently testing against my own (admittedly feeble) solutions

Requires node >=4.12

**Comment by atesgoral** [comment]
:+1: :+1: :+1: 

I was also toying around with the idea of implementing an interpreter. This will be useful! :)

**Comment by nrkn** [comment]
Cool - there may be some bugs still - I'm still playing the game - for example I just got to Inventory Report and discovered that you can add/sub strings, the test failed, so I've just fixed that :)

**Comment by atesgoral** [comment]
SO IT BEGINS.

```
npm install
gulp
```

@nrkn For now I've directly tapped into the test folder that's installed by hrm-cpu for the level environment data. I might clone that into a test folder in this repo. Or maybe a common npm module could be useful. It could be nice to also capture the size/speed par values by level in these files.

**Comment by nrkn** [comment]
Cool! 

There is a verbose flag you can use to get more than just the output:

```javascript
const info = hrm( source, inbox, floor, true ) //you can pass {} or [] for an empty floor
```

You'll get an object like:

```json
{
	"accumulator" : 0,
	"memory" : [],
	"outbox" : [0, 0, 0, 0],
	"size" : 5,
	"steps" : 28
}
```

**Comment by nrkn** [comment]
Wait, I think I misunderstood you - did you mean it might be nice to add the pars to the .json containing the test data?

**Comment by atesgoral** [comment]
Yes, if you think that that's a valid place for them. Though, I don't think hrm-cpu should care about pars. So, yeah, maybe the game-specific level/par info belongs either to this repo or a common repo that can be imported (`npm install hrm-level-data`) etc.

**Comment by nrkn** [comment]
Yeah I was just looking at the gulpfile between when I posted last and you posted that!

I agree it should go in a 2nd repo, but there are a couple of issues with the test file atm, firstly that it's incomplete (I've played quite a few since I last pushed repo/published package though, they can go out soon - just about to play Digit Exploder now) and secondly that it really should do what HRM does and test each asm against multiple input/outputs - you can't be sure the asm is correct against just one set :/

**Comment by atesgoral** [comment]
@nrkn There are a lot of good folks among the contributors to this repo who have not only finished the entire game, but have played and hacked and slashed each level a number of times :) Once we initiate a repo for level data, I'm sure we can collectively populate it with the entire level data.

**Comment by atesgoral** [comment]
Here we go... https://github.com/atesgoral/hrm-level-data

**Comment by nrkn** [comment]
Good point - 

So I guess it could be something like:

```json
  "Mail-Room": {
    "floor": {},
    "expect": [
      {
        "inbox": [ 1, 9, 4 ],    
        "outbox": [ 1, 9, 4 ]        
      },
      {
        "inbox": [ 1, 2, 3 ],    
        "outbox": [ 1, 2, 3 ]        
      },
      {
        "inbox": [ 3, 2, 1 ],    
        "outbox": [ 3, 2, 1 ]        
      }      
    ]
  }
```

**Comment by nrkn** [comment]
I'm gonna be offline for a while but will check in later

**Comment by atesgoral** [comment]
https://github.com/atesgoral/hrm-level-data/blob/master/index.json

I didn't want to use the level names as a key. In fact, even the level number is not a key. This will make lookups a little inconvenient, but reduces the number of assumptions/dependencies.

**Comment by atesgoral** [comment]
`npm install hrm-level-data` :)

**Comment by nrkn** [comment]
Awesome, deleted my fork

I added all the data I have in a new branch

**Comment by atesgoral** [comment]
Tracking as separate issues #104, #105, #106, #107, #108, #109
